version: '3.8'
services:
  smstestapp.api:
    image: ${DOCKER_REGISTRY-}smstestapp-api
    build:
      context: .
      dockerfile: SmsTestApp.Api/Dockerfile

  smstestapp.db:
    image: postgres:15
    
  smstestapp.dbadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - smstestapp.db
